approval_policy = "on-request"
sandbox_mode = "workspace-write"

model = "gpt-5.2-codex"
model_reasoning_effort = "high"

[features]
web_search_request = true
collab = true
collaboration_modes = true
